(() => {
  const money = (value) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(Number(value) || 0);
  const pct = (value) => `${Number(value || 0).toFixed(1).replace('.', ',')}%`;
  const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[c]));
  const session = () => { try { return JSON.parse(sessionStorage.getItem('clareza_supabase_session') || 'null'); } catch { return null; } };
  const categoryOf = (row) => row.raw_data?.category || row.category || 'Outros';
  const dateOf = (row) => row.transaction_date || '';
  const loadRows = async () => { const [transactions, imported] = await Promise.all([window.clarezaDb.select('transactions', '?select=*'), window.clarezaDb.select('import_rows', '?review_status=eq.approved&select=*')]); return [...transactions, ...imported.map((row) => ({ ...row, category: categoryOf(row), description: row.normalized_description || row.original_description, transaction_date: dateOf(row), source: 'import' }))]; };
  const render = async () => {
    if (window.financeState?.view !== 'analysis' || !window.clarezaDb || !session()) return;
    const content = document.getElementById('content'); if (!content || content.dataset.analysisRendered === 'true') return;
    content.dataset.analysisRendered = 'true'; document.getElementById('page-title').textContent = 'Análise financeira';
    try {
      const rows = (await loadRows()).filter((row) => row.type !== 'income' && Number(row.amount) > 0);
      const incomes = (await loadRows()).filter((row) => row.type === 'income').reduce((sum, row) => sum + Number(row.amount || 0), 0);
      const total = rows.reduce((sum, row) => sum + Number(row.amount || 0), 0);
      const byCategory = Object.values(rows.reduce((map, row) => { const category = categoryOf(row); const item = map[category] ||= { category, total: 0, count: 0, max: 0, last: '' }; item.total += Number(row.amount || 0); item.count++; item.max = Math.max(item.max, Number(row.amount || 0)); item.last = row.transaction_date || item.last; return map; }, {})).sort((a, b) => b.total - a.total);
      const months = Object.values(rows.reduce((map, row) => { const month = String(row.transaction_date || '').slice(0, 7) || 'Sem data'; map[month] ||= { month, total: 0 }; map[month].total += Number(row.amount || 0); return map; }, {})).sort((a, b) => a.month.localeCompare(b.month));
      const merchants = Object.values(rows.reduce((map, row) => { const name = row.merchant_name || row.merchant || row.description || 'Não identificado'; map[name] ||= { name, total: 0, count: 0 }; map[name].total += Number(row.amount || 0); map[name].count++; return map; }, {})).sort((a, b) => b.total - a.total).slice(0, 8);
      const top = byCategory[0], second = byCategory[1];
      const insights = [top ? `${top.category} concentra ${pct(top.total / (total || 1) * 100)} das despesas.` : 'Ainda não há despesas suficientes para gerar insights.', second && top.total > second.total * 1.25 ? `${top.category} está bem acima da segunda categoria, ${second.category}.` : 'A distribuição entre categorias está relativamente equilibrada.', rows.filter((row) => Number(row.amount) > (total / (rows.length || 1)) * 2).length ? 'Existem lançamentos acima do ticket médio para revisar.' : 'Não foram encontrados lançamentos muito acima do ticket médio.'];
      content.innerHTML = `<div class="analysis-page"><div class="section-title"><div><h2>Para onde está indo meu dinheiro?</h2><p class="muted">Análise baseada nos lançamentos oficiais e importações aprovadas.</p></div><span class="pill">${rows.length} despesas analisadas</span></div><div class="metrics">${metric('DESPESAS', money(total), `${rows.length} lançamentos`, 'down')}${metric('RECEITAS', money(incomes), 'dados disponíveis', 'up')}${metric('RENDA COMPROMETIDA', pct(incomes ? total / incomes * 100 : 0), 'despesas ÷ receitas', total > incomes ? 'down' : 'up')}${metric('TICKET MÉDIO', money(total / (rows.length || 1)), 'por lançamento', '')}</div><div class="analysis-grid"><section class="card"><div class="card-head"><h3>Gastos por categoria</h3><span class="muted">Participação no total</span></div>${byCategory.length ? byCategory.slice(0, 10).map((item) => `<div class="analysis-category"><div><strong>${esc(item.category)}</strong><small>${item.count} lançamentos · média ${money(item.total / item.count)}</small></div><div class="analysis-bar"><i style="width:${Math.max(3, item.total / (total || 1) * 100)}%"></i></div><b>${money(item.total)}</b><span>${pct(item.total / (total || 1) * 100)}</span></div>`).join('') : '<p class="empty-note">Nenhuma despesa real encontrada.</p>'}</section><section class="card"><div class="card-head"><h3>O que chamou atenção este mês</h3></div><div class="insight-list">${insights.map((item) => `<div class="insight-item"><span>✦</span><p>${esc(item)}</p></div>`).join('')}</div></section></div><div class="analysis-grid"><section class="card"><div class="card-head"><h3>Evolução mensal</h3></div><div class="analysis-months">${months.length ? months.map((item) => `<div><span>${esc(item.month)}</span><div class="analysis-bar"><i style="width:${Math.max(4, item.total / (Math.max(...months.map((m) => m.total)) || 1) * 100)}%"></i></div><b>${money(item.total)}</b></div>`).join('') : '<p class="empty-note">Datas pendentes para comparação mensal.</p>'}</div></section><section class="card"><div class="card-head"><h3>Maiores estabelecimentos</h3></div>${merchants.length ? merchants.map((item, index) => `<div class="merchant-rank"><span>${index + 1}</span><strong>${esc(item.name)}</strong><small>${item.count} ocorrências</small><b>${money(item.total)}</b></div>`).join('') : '<p class="empty-note">Nenhum estabelecimento identificado.</p>'}</section></div></div>`;
    } catch (error) { content.dataset.analysisRendered = 'true'; content.innerHTML = `<div class="card"><h2>Não foi possível carregar a análise</h2><p class="muted">${esc(error.message)}</p></div>`; }
  };
  const observer = new MutationObserver(() => { const content = document.getElementById('content'); if (window.financeState?.view !== 'analysis' && content) delete content.dataset.analysisRendered; render(); });
  observer.observe(document.getElementById('content'), { childList: true, subtree: true }); render();
})();
