(() => {
  const state = window.financeState;
  const render = window.financeView;
  if (!state || !render) return;
  const storageKey = 'clareza_manual_receivables';
  const readReceivables = () => { try { return JSON.parse(localStorage.getItem(storageKey) || '[]'); } catch { return []; } };
  let receivables = readReceivables();
  const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const money = (value) => new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(value)||0);
  const toast = (message, error = false) => { const node=document.createElement('div'); node.className=`feature-toast${error?' error':''}`; node.textContent=message; document.body.append(node); setTimeout(()=>node.remove(),3200); };
  const modal = (title, body) => { const wrap=document.createElement('div'); wrap.className='feature-modal open'; wrap.innerHTML=`<div class="modal"><button class="modal-close" type="button" aria-label="Fechar">×</button><h2>${title}</h2>${body}</div>`; document.body.append(wrap); const close=()=>wrap.remove(); wrap.querySelector('.modal-close').onclick=close; wrap.onclick=(event)=>{if(event.target===wrap)close()}; return {wrap,close}; };
  const enhanceTransactions = () => {
    const table=document.querySelector('.data-table'); if(!table || state.view!=='transactions' || table.dataset.enhanced==='true') return;
    table.dataset.enhanced='true'; const head=document.createElement('th'); head.textContent='AÇÕES'; table.tHead.rows[0].append(head);
    [...table.tBodies[0].rows].forEach((row, index) => { const entry=state.entries[index]; if(!entry)return; row.dataset.entryIndex=index; const cell=row.insertCell(); cell.innerHTML=`<div class="row-actions"><button class="table-action" data-action="edit-entry" data-index="${index}">Editar</button><button class="table-action danger" data-action="delete-entry" data-index="${index}">Excluir</button></div>`; });
  };
  const showEdit = (index) => { const entry=state.entries[index]; if(!entry)return; const {wrap,close}=modal('Editar lançamento',`<form class="feature-form" id="edit-feature-form"><div class="form-grid"><label>Tipo<select name="type"><option value="expense" ${entry.type==='expense'?'selected':''}>Despesa</option><option value="income" ${entry.type==='income'?'selected':''}>Receita</option></select></label><label>Descrição<input required name="description" value="${escapeHtml(entry.description)}" /></label><label>Valor<input required min="0" name="amount" type="number" step="0.01" value="${entry.amount}" /></label><label>Categoria<input name="category" value="${escapeHtml(entry.category)}" /></label><label>Data<input required name="date" type="date" value="${entry.date}" /></label><label>Status<select name="status"><option ${entry.status==='Pago'?'selected':''}>Pago</option><option ${entry.status==='Pendente'?'selected':''}>Pendente</option><option ${entry.status==='Previsto'?'selected':''}>Previsto</option></select></label></div><button class="primary full" type="submit">Salvar alterações</button></form>`); wrap.querySelector('form').onsubmit=(event)=>{event.preventDefault();const data=new FormData(event.currentTarget);state.entries[index]={...entry,type:data.get('type'),description:data.get('description'),amount:Number(data.get('amount')),category:data.get('category'),date:data.get('date'),status:data.get('status')};close();render();toast('Lançamento atualizado.');}; };
  const showReceivables = () => { state.view='receivables'; document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view==='receivables')); const total=receivables.reduce((sum,r)=>sum+r.amount,0), received=receivables.filter(r=>r.status==='Recebido').reduce((sum,r)=>sum+r.amount,0); document.getElementById('page-title').textContent='Recebíveis'; document.getElementById('content').innerHTML=`<div class="section-title"><div><h2>Receitas e recebíveis</h2><p class="muted">Cadastre valores que ainda serão recebidos e acompanhe seus prazos.</p></div><button class="primary" id="new-receivable">+ Novo recebível</button></div><div class="receivable-summary"><div class="metric"><div class="metric-label">TOTAL PREVISTO</div><div class="metric-value">${money(total)}</div></div><div class="metric"><div class="metric-label">RECEBIDO</div><div class="metric-value up">${money(received)}</div></div><div class="metric"><div class="metric-label">A RECEBER</div><div class="metric-value">${money(total-received)}</div></div></div><div class="card"><div class="table-wrap"><table class="data-table"><thead><tr><th>DESCRIÇÃO</th><th>VALOR</th><th>DATA PREVISTA</th><th>CERTEZA</th><th>STATUS</th><th>AÇÕES</th></tr></thead><tbody>${receivables.length?receivables.map((r,i)=>`<tr class="${r.deleted?'row-muted':''}"><td><strong>${escapeHtml(r.description)}</strong></td><td class="up">${money(r.amount)}</td><td>${new Date(r.dueDate+'T12:00:00').toLocaleDateString('pt-BR')}</td><td>${escapeHtml(r.certainty)}</td><td><span class="receivable-status ${r.status==='Recebido'?'received':''}">${r.status}</span></td><td><div class="row-actions"><button class="table-action" data-action="edit-receivable" data-index="${i}">Editar</button><button class="table-action danger" data-action="delete-receivable" data-index="${i}">Excluir</button></div></td></tr>`).join(''):'<tr><td colspan="6" class="empty-note">Nenhum recebível cadastrado.</td></tr>'}</tbody></table></div></div>`; document.getElementById('new-receivable').onclick=()=>showReceivableForm(); };
  const showReceivableForm = (index=null) => { const item=index===null?{description:'',amount:'',dueDate:'',certainty:'Confirmado',status:'Previsto'}:receivables[index]; const {wrap,close}=modal(index===null?'Novo recebível':'Editar recebível',`<form class="feature-form" id="receivable-form"><div class="form-grid"><label>Descrição<input required name="description" value="${escapeHtml(item.description)}" placeholder="Ex.: Salário" /></label><label>Valor<input required min="0" name="amount" type="number" step="0.01" value="${item.amount}" /></label><label>Data prevista<input required name="dueDate" type="date" value="${item.dueDate}" /></label><label>Nível de certeza<select name="certainty"><option ${item.certainty==='Confirmado'?'selected':''}>Confirmado</option><option ${item.certainty==='Provável'?'selected':''}>Provável</option><option ${item.certainty==='Possível'?'selected':''}>Possível</option></select></label><label>Status<select name="status"><option ${item.status==='Previsto'?'selected':''}>Previsto</option><option ${item.status==='Recebido'?'selected':''}>Recebido</option><option ${item.status==='Atrasado'?'selected':''}>Atrasado</option></select></label></div><button class="primary full" type="submit">Salvar recebível</button></form>`); wrap.querySelector('form').onsubmit=(event)=>{event.preventDefault();const d=new FormData(event.currentTarget);const value={description:d.get('description'),amount:Number(d.get('amount')),dueDate:d.get('dueDate'),certainty:d.get('certainty'),status:d.get('status')}; if(index===null)receivables.unshift(value);else receivables[index]=value; localStorage.setItem(storageKey,JSON.stringify(receivables));close();showReceivables();toast('Recebível salvo.');}; };
  const addNav = () => { if(document.querySelector('[data-view="receivables"]'))return; const nav=document.getElementById('nav'); const button=document.createElement('button'); button.className='nav-item'; button.dataset.view='receivables'; button.innerHTML='<span>↗</span> Recebíveis'; button.onclick=showReceivables; nav.insertBefore(button,nav.children[1]); };
  document.addEventListener('click',(event)=>{const button=event.target.closest('[data-action]'); if(!button)return; const index=Number(button.dataset.index); if(button.dataset.action==='edit-entry')showEdit(index); if(button.dataset.action==='delete-entry'&&confirm('Excluir logicamente este lançamento?')){state.entries[index].deleted=true;render();toast('Lançamento excluído.');} if(button.dataset.action==='edit-receivable')showReceivableForm(index); if(button.dataset.action==='delete-receivable'&&confirm('Excluir logicamente este recebível?')){receivables[index].deleted=true;localStorage.setItem(storageKey,JSON.stringify(receivables));showReceivables();toast('Recebível excluído.');}});
  const bindInactiveButtons = () => document.querySelectorAll('button').forEach((button) => { if (button.dataset.bound || button.type === 'submit' || button.id || button.dataset.view || button.dataset.action || button.classList.contains('modal-close')) return; button.dataset.bound='true'; button.addEventListener('click', () => toast('Esta opção está disponível na próxima etapa do módulo.')); });
  addNav(); const observer=new MutationObserver(()=>{enhanceTransactions();bindInactiveButtons();}); observer.observe(document.getElementById('content'),{childList:true,subtree:true}); enhanceTransactions(); bindInactiveButtons();
})();
