(() => {
  const DRAFT_KEY = 'clareza_itau_review_drafts_v1';
  const invoices = [
    ['Fatura_Itau_20260711-111038.pdf','01/2026','2444','10/01/2026',1684.37],
    ['Fatura_Itau_20260711-111101.pdf','02/2026','9362','10/02/2026',2036.02],
    ['Fatura_Itau_20260711-111117.pdf','03/2026','9362','10/03/2026',2098.13],
    ['Fatura_Itau_20260711-111134.pdf','04/2026','9362','10/04/2026',2690.03],
    ['Fatura_Itau_20260711-111301.pdf','05/2026','9362','11/05/2026',2047.68],
    ['Fatura_Itau_20260711-112244.pdf','06/2026','9362','10/06/2026',2565.56],
    ['Fatura_Itau_20260711-112258.pdf','07/2026','9362','10/07/2026',2348.42],
    ['Fatura_Itau_20260711-114329.pdf','01/2026','0413','10/01/2026',1146.11],
    ['Fatura_Itau_20260711-114345.pdf','02/2026','0413','10/02/2026',1404.20],
    ['Fatura_Itau_20260711-114433.pdf','04/2026','0413','10/04/2026',842.97],
    ['Fatura_Itau_20260711-114451.pdf','05/2026','0413','10/05/2026',1325.58],
    ['Fatura_Itau_20260711-114508.pdf','06/2026','0413','10/06/2026',1776.43],
    ['Fatura_Itau_20260711-114526.pdf','07/2026','0413','10/07/2026',2023.37]
  ].map(([filename,month,lastFour,due,total]) => ({filename,month,lastFour,due,total,status:'Pendente'}));
  const categories=['Moradia','Alimentação','Transporte','Saúde','Educação','Lazer','Compras','Assinaturas e serviços','Financeiro','Família','Outros'];
  const types=['Compra','Parcela','Crédito','Estorno','Pagamento','Juros','Tarifa','Ajuste','Outro'];
  const esc=(v)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const money=(v)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0);
  const load=()=>{try{return JSON.parse(localStorage.getItem(DRAFT_KEY)||'{}')}catch{return {}}};
  const drafts=load(); let selected=0; const pdfUrls={};
  const rowsFor=(invoice)=>drafts[invoice.filename]?.rows||[];
  const signed=(row)=>['Crédito','Estorno','Pagamento'].includes(row.type)?-Math.abs(Number(row.amount)||0):Math.abs(Number(row.amount)||0);
  const totals=(invoice)=>{const rows=rowsFor(invoice),conciled=rows.reduce((s,r)=>s+signed(r),0),credits=rows.filter(r=>r.type==='Crédito').reduce((s,r)=>s+Math.abs(Number(r.amount)||0),0),refunds=rows.filter(r=>r.type==='Estorno').reduce((s,r)=>s+Math.abs(Number(r.amount)||0),0);return{rows,conciled,credits,refunds,difference:Number((invoice.total-conciled).toFixed(2)),percent:invoice.total?Math.max(0,Math.min(100,conciled/invoice.total*100)):0}};
  const persist=(invoice,status)=>{drafts[invoice.filename]={...(drafts[invoice.filename]||{}),rows:rowsFor(invoice),status:status||drafts[invoice.filename]?.status||'Em revisão',updatedAt:new Date().toISOString()};localStorage.setItem(DRAFT_KEY,JSON.stringify(drafts));};
  const rowForm=(row={})=>`<form id="manual-row-form" class="feature-form"><div class="form-grid review-form-grid"><label>Data<input required type="date" name="date" value="${esc(row.date)}"></label><label>Descrição original<input required name="original" value="${esc(row.original)}"></label><label>Descrição normalizada<input name="normalized" value="${esc(row.normalized)}"></label><label>Estabelecimento<input name="merchant" value="${esc(row.merchant)}"></label><label>Valor<input required min="0" step="0.01" type="number" name="amount" value="${esc(row.amount)}"></label><label>Tipo<select name="type">${types.map(t=>`<option ${row.type===t?'selected':''}>${t}</option>`).join('')}</select></label><label>Categoria<select name="category"><option value="">Selecionar</option>${categories.map(c=>`<option ${row.category===c?'selected':''}>${c}</option>`).join('')}</select></label><label>Subcategoria<input name="subcategory" value="${esc(row.subcategory)}"></label><label>Parcela atual<input min="1" type="number" name="installmentNumber" value="${esc(row.installmentNumber)}"></label><label>Total de parcelas<input min="1" type="number" name="installmentTotal" value="${esc(row.installmentTotal)}"></label><label>Confiança<select name="confidence"><option>Alta</option><option selected>Média</option><option>Baixa</option><option>Não classificado</option></select></label><label>Página de origem<input min="1" type="number" name="page" value="${esc(row.page)}"></label><label class="wide">Observação<textarea name="note">${esc(row.note)}</textarea></label></div><button class="primary full" type="submit">Salvar linha no rascunho</button></form>`;
  const showModal=(title,html,onSubmit)=>{const node=document.createElement('div');node.className='feature-modal open';node.innerHTML=`<div class="modal review-modal"><button class="modal-close" aria-label="Fechar">×</button><h2>${title}</h2>${html}</div>`;document.body.append(node);node.querySelector('.modal-close').onclick=()=>node.remove();node.querySelector('form').onsubmit=e=>{e.preventDefault();onSubmit(new FormData(e.currentTarget));node.remove();renderWorkspace();};};
  const editRow=(index=null,duplicate=false)=>{const invoice=invoices[selected],base=index===null?{}:{...rowsFor(invoice)[index]};if(duplicate)delete base.id;showModal(index===null?'Adicionar linha':duplicate?'Duplicar linha':'Editar linha',rowForm(base),data=>{const row=Object.fromEntries(data.entries());row.id=crypto.randomUUID();row.amount=Number(row.amount);if(index===null||duplicate)rowsFor(invoice).push(row);else rowsFor(invoice)[index]=row;persist(invoice,'Em revisão');});};
  const validate=(invoice)=>{const t=totals(invoice);const invalid=t.rows.some(r=>!r.date||!r.original||!r.category||!r.type||!(Number(r.amount)>=0));if(!t.rows.length)return'Adicione os lançamentos da fatura.';if(invalid)return'Preencha data, descrição, valor, tipo e categoria de todas as linhas.';if(Math.abs(t.difference)>0.01)return`Existe diferença de ${money(t.difference)}. Corrija ou documente antes de concluir.`;return'';};
  const renderWorkspace=()=>{const host=document.getElementById('itau-review');if(!host)return;const inv=invoices[selected],t=totals(inv),status=drafts[inv.filename]?.status||'Pendente';host.innerHTML=`<div class="review-header card"><div><small>ITAÚ • CARTÃO FINAL ${inv.lastFour}</small><h3>${inv.month} — ${money(inv.total)}</h3><span>Vencimento ${inv.due} · ${esc(inv.filename)}</span></div><div class="review-totals"><b>${money(t.conciled)}</b><small>Total digitado</small><b class="${Math.abs(t.difference)<=.01?'up':'down'}">${money(t.difference)}</b><small>Diferença restante</small></div></div><div class="review-progress"><span style="width:${t.percent}%"></span></div><div class="review-split"><section class="pdf-pane card">${pdfUrls[inv.filename]?`<iframe title="Fatura ${esc(inv.month)}" src="${pdfUrls[inv.filename]}"></iframe>`:'<div class="pdf-placeholder"><strong>PDF local não vinculado</strong><p>Selecione a pasta das faturas para visualizar este arquivo lado a lado.</p></div>'}</section><section class="review-editor card"><div class="section-title"><div><h3>Lançamentos em revisão</h3><p class="muted">${t.rows.length} linhas · Status: ${status}</p></div><button class="primary" id="add-manual-row">+ Adicionar linha</button></div><div class="table-wrap"><table class="data-table"><thead><tr><th>DATA</th><th>DESCRIÇÃO</th><th>TIPO</th><th>CATEGORIA</th><th>VALOR</th><th>AÇÕES</th></tr></thead><tbody>${t.rows.length?t.rows.map((r,i)=>`<tr><td>${esc(r.date)}</td><td><strong>${esc(r.original)}</strong><small>${esc(r.normalized||r.merchant||'')}</small></td><td>${esc(r.type)}</td><td>${esc(r.category||'Pendente')}</td><td class="${signed(r)<0?'up':''}">${money(signed(r))}</td><td><div class="row-actions"><button data-edit="${i}">Editar</button><button data-copy="${i}">Duplicar</button><button data-delete="${i}" class="danger">Excluir</button></div></td></tr>`).join(''):'<tr><td colspan="6" class="empty-note">Nenhuma linha digitada.</td></tr>'}</tbody></table></div><div class="reconciliation"><span>Créditos: <b>${money(t.credits)}</b></span><span>Estornos: <b>${money(t.refunds)}</b></span><span>Oficial: <b>${money(inv.total)}</b></span></div><label>Justificativa de diferença<textarea id="difference-note" placeholder="Somente para diferenças estruturalmente válidas">${esc(drafts[inv.filename]?.differenceNote||'')}</textarea></label><div class="review-actions"><button id="save-review" class="secondary">Salvar rascunho</button><button id="validate-review" class="secondary">Validar total</button><button id="complete-review" class="primary">Concluir revisão</button></div><p id="review-message" role="alert"></p></section></div>`;
    host.querySelector('#add-manual-row').onclick=()=>editRow();host.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editRow(Number(b.dataset.edit)));host.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>editRow(Number(b.dataset.copy),true));host.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(confirm('Excluir esta linha do rascunho?')){rowsFor(inv).splice(Number(b.dataset.delete),1);persist(inv,'Parcialmente revisada');renderWorkspace();}});host.querySelector('#save-review').onclick=()=>{persist(inv,t.rows.length?'Parcialmente revisada':'Pendente');renderWorkspace();};host.querySelector('#validate-review').onclick=()=>{host.querySelector('#review-message').textContent=validate(inv)||'Total conciliado e campos obrigatórios válidos.';};host.querySelector('#complete-review').onclick=()=>{const error=validate(inv);host.querySelector('#review-message').textContent=error||'Revisão conciliada. Ainda aguarda aprovação final.';if(!error){drafts[inv.filename].differenceNote=host.querySelector('#difference-note').value;persist(inv,'Conciliada');renderWorkspace();}};
  };
  const renderImport=()=>{const content=document.getElementById('content');if(!content||window.financeState?.view!=='import')return;const duplicate='Nubank_2026-03-16 (1).pdf';content.innerHTML=`<div class="section-title"><div><h2>Dados em revisão</h2><p class="muted">${invoices.length} faturas Itaú aguardam digitação e conciliação. Nenhum rascunho entra no dashboard.</p></div><label class="primary import-picker">Vincular PDFs<input id="invoice-files" type="file" accept="application/pdf,.pdf" multiple hidden></label></div><div class="card duplicate-alert"><strong>Duplicata de arquivo — não importar</strong><span>${duplicate} é idêntico a Nubank_2026-03-16.pdf · 36.171 bytes · SHA-256 5166b838cf24f9395c20e8326d2fa935d4cab9f9aad05a5c3171f379f6251f42.</span></div><div class="invoice-tabs">${invoices.map((inv,i)=>`<button data-invoice="${i}" class="${i===selected?'active':''}"><b>${inv.month}</b><span>•••• ${inv.lastFour}</span><small>${drafts[inv.filename]?.status||'Pendente'}</small></button>`).join('')}</div><div id="itau-review"></div>`;content.querySelectorAll('[data-invoice]').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.invoice);renderImport();});content.querySelector('#invoice-files').onchange=e=>{[...e.target.files].forEach(file=>{if(pdfUrls[file.name])URL.revokeObjectURL(pdfUrls[file.name]);pdfUrls[file.name]=URL.createObjectURL(file);});renderWorkspace();};renderWorkspace();};
  const observer=new MutationObserver(renderImport);observer.observe(document.getElementById('content'),{childList:true,subtree:false});renderImport();
})();
