(() => {
  const key = 'clareza_operations_draft';
  const read = () => { try { return JSON.parse(localStorage.getItem(key) || '{"expenses":[],"predictions":[]}'); } catch { return { expenses: [], predictions: [] }; } };
  const state = read();
  const esc = (v) => String(v ?? '').replace(/[&<>"']/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const money = (v) => new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0);
  const modal = (title, body, onSubmit) => { const node=document.createElement('div'); node.className='feature-modal open'; node.innerHTML=`<div class="modal"><button class="modal-close" type="button" aria-label="Fechar">×</button><h2>${title}</h2>${body}</div>`; document.body.append(node); node.querySelector('.modal-close').onclick=()=>node.remove(); node.querySelector('form').onsubmit=(e)=>{e.preventDefault();onSubmit(new FormData(e.currentTarget));node.remove();}; };
  const form = (kind) => `<form class="feature-form"><div class="form-grid"><label>Descrição<input required name="description"></label><label>Valor<input required min="0" step="0.01" type="number" name="amount"></label><label>Data<input required type="date" name="date"></label><label>Categoria<input name="category" placeholder="Ex.: Alimentação"></label><label>Status<select name="status"><option>Previsto</option><option>Pendente</option><option>Pago</option></select></label>${kind==='prediction'?'<label>Certeza<select name="certainty"><option>Confirmado</option><option>Provável</option><option>Possível</option></select></label>':''}</div><button class="primary full" type="submit">Salvar rascunho</button></form>`;
  const save = () => localStorage.setItem(key, JSON.stringify(state));
  const addActions = () => { const target=document.querySelector('.top-actions'); if(!target || target.dataset.ops)return; target.dataset.ops='true'; const btn=document.createElement('button'); btn.className='secondary'; btn.textContent='+ Despesa'; btn.onclick=()=>modal('Adicionar despesa',form('expense'),(d)=>{state.expenses.push({description:d.get('description'),amount:Number(d.get('amount')),date:d.get('date'),category:d.get('category'),status:d.get('status')});save();alert('Despesa salva como rascunho local.');}); target.insertBefore(btn,target.firstChild); const pred=document.createElement('button'); pred.className='secondary'; pred.textContent='+ Previsão'; pred.onclick=()=>modal('Adicionar previsão de gasto',form('prediction'),(d)=>{state.predictions.push({description:d.get('description'),amount:Number(d.get('amount')),date:d.get('date'),category:d.get('category'),certainty:d.get('certainty')});save();alert('Previsão salva como rascunho local.');}); target.insertBefore(pred,target.firstChild); };
  const observer=new MutationObserver(addActions); observer.observe(document.body,{childList:true,subtree:true}); addActions();
  window.clarezaOperations = { state, money };
})();
