(() => {
  const money = (value) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(Number(value) || 0);
  const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[c]));
  const hasSession = () => { try { return Boolean(JSON.parse(sessionStorage.getItem('clareza_supabase_session') || 'null')?.access_token); } catch { return false; } };
  let loading = false;
  const query = (table) => window.clarezaDb.select(table, '?select=*');
  const empty = (title, text, action) => `<div class="card empty-module"><h2>${title}</h2><p class="muted">${text}</p>${action ? `<button class="primary" id="module-action">${action}</button>` : ''}</div>`;
  const render = async () => {
    const view = window.financeState?.view, content = document.getElementById('content');
    if (loading || !content || !hasSession() || !window.clarezaDb || !['cards', 'projection', 'budget', 'goals'].includes(view) || content.dataset.realModule === view) return;
    loading = true; content.dataset.realModule = view;
    try {
      if (view === 'cards') { const [cards, invoices] = await Promise.all([query('credit_cards'), query('invoices')]); content.innerHTML = `<div class="section-title"><div><h2>Cartões e faturas</h2><p class="muted">Dados reais cadastrados no Supabase.</p></div></div>${cards.length || invoices.length ? `<div class="card"><div class="table-wrap"><table class="data-table"><thead><tr><th>CARTÃO</th><th>EMISSOR</th><th>FINAL</th><th>FATURAS</th></tr></thead><tbody>${cards.map((card) => `<tr><td><strong>${esc(card.name)}</strong></td><td>${esc(card.issuer || '—')}</td><td>•••• ${esc(card.last_four || '—')}</td><td>${invoices.filter((invoice) => invoice.credit_card_id === card.id).length}</td></tr>`).join('') || '<tr><td colspan="4">Nenhum cartão cadastrado.</td></tr>'}</tbody></table></div></div>` : empty('Nenhum cartão cadastrado', 'Cadastre um cartão para acompanhar faturas, limite e parcelas reais.')}`; }
      if (view === 'projection') { const [transactions, receivables, predictions] = await Promise.all([query('transactions'), query('receivables'), query('future_expense_predictions')]); const income = transactions.filter((item) => item.type === 'income').reduce((sum, item) => sum + Number(item.amount || 0), 0); const expenses = transactions.filter((item) => item.type !== 'income').reduce((sum, item) => sum + Number(item.amount || 0), 0); content.innerHTML = `<div class="section-title"><div><h2>Projeção financeira</h2><p class="muted">Projeção calculada com dados reais disponíveis.</p></div></div><div class="metrics">${metric('RECEITAS', money(income), `${transactions.filter((item) => item.type === 'income').length} registros`, 'up')}${metric('DESPESAS', money(expenses), `${transactions.filter((item) => item.type !== 'income').length} registros`, 'down')}${metric('RECEBÍVEIS', money(receivables.reduce((sum, item) => sum + Number(item.expected_amount || 0), 0)), `${receivables.length} registros`, '')}${metric('PREVISÕES', money(predictions.reduce((sum, item) => sum + Number(item.estimated_amount || 0), 0)), `${predictions.length} registros`, '')}</div>${transactions.length || receivables.length || predictions.length ? '<div class="card"><p class="muted">A projeção detalhada por cenário será calculada a partir desses registros reais.</p></div>' : empty('Sem dados para projetar', 'Adicione lançamentos, recebíveis ou previsões para gerar a projeção.')}`; }
      if (view === 'budget') content.innerHTML = `<div class="section-title"><div><h2>Orçamento mensal</h2><p class="muted">Defina limites por categoria para acompanhar o consumo real.</p></div></div>${empty('Orçamento ainda não configurado', 'Nenhum orçamento real está cadastrado. Os valores demonstrativos foram removidos.')}`;
      if (view === 'goals') content.innerHTML = `<div class="section-title"><div><h2>Metas financeiras</h2><p class="muted">Acompanhe metas vinculadas aos seus dados reais.</p></div></div>${empty('Nenhuma meta cadastrada', 'As metas demonstrativas foram removidas. Cadastre sua primeira meta para acompanhar o progresso.')}`;
    } catch (error) { content.innerHTML = `<div class="card"><h2>Não foi possível carregar esta área</h2><p class="muted">${esc(error.message)}</p></div>`; }
    finally { loading = false; }
  };
  const observer = new MutationObserver(() => { const content = document.getElementById('content'); if (content && !['cards', 'projection', 'budget', 'goals'].includes(window.financeState?.view)) delete content.dataset.realModule; render(); });
  observer.observe(document.getElementById('content'), { childList: true, subtree: true }); render();
})();
