(() => {
  const draftKey='clareza_itau_review_drafts_v1'; const sessionKey='clareza_supabase_session';
  const getSession=()=>{try{return JSON.parse(sessionStorage.getItem(sessionKey)||'null')}catch{return null}};
  const userId=()=>{const token=getSession()?.access_token;if(!token)return null;try{return JSON.parse(atob(token.split('.')[1].replace(/-/g,'+').replace(/_/g,'/'))).sub}catch{return null}};
  const read=()=>{try{return JSON.parse(localStorage.getItem(draftKey)||'{}')}catch{return {}}};
  const notify=(message,error=false)=>{const node=document.createElement('div');node.className=`feature-toast${error?' error':''}`;node.textContent=message;document.body.append(node);setTimeout(()=>node.remove(),3500)};
  const addButtons=()=>{if(window.financeState?.view!=='import'||document.getElementById('remote-draft-actions'))return;const target=document.querySelector('.section-title');if(!target)return;const box=document.createElement('div');box.id='remote-draft-actions';box.className='remote-draft-actions';box.innerHTML='<button class="secondary" type="button" id="sync-drafts">Salvar revisão no Supabase</button><button class="secondary" type="button" id="load-drafts">Carregar revisão salva</button>';target.append(box);box.querySelector('#sync-drafts').onclick=sync;box.querySelector('#load-drafts').onclick=loadRemote;};
  const sync=async()=>{if(!window.clarezaDb)return notify('Cliente Supabase indisponível.',true);const uid=userId();if(!uid)return notify('Entre novamente para sincronizar a revisão.',true);const drafts=read();const entries=Object.entries(drafts).filter(([name,value])=>name!=='_files'&&value?.rows?.length);if(!entries.length)return notify('Não há linhas em rascunho para sincronizar.',true);const batch=(await window.clarezaDb.insert('import_batches',[{user_id:uid,status:'review',file_count:entries.length,row_count:entries.reduce((n,[,v])=>n+v.rows.length,0),source:'manual_review'}]))[0];for(const [filename,draft] of entries){const fileMeta=drafts._files?.[filename];let file=null;if(fileMeta){try{file=(await window.clarezaDb.insert('import_files',[{user_id:uid,import_batch_id:batch.id,filename,mime_type:'application/pdf',file_hash:fileMeta.hash,file_size:fileMeta.size,parser_status:'needs_review'}]))[0]}catch{const found=await window.clarezaDb.select('import_files',`?user_id=eq.${uid}&file_hash=eq.${fileMeta.hash}&limit=1`);file=found[0]||null;}}for(const row of draft.rows){await window.clarezaDb.insert('import_rows',[{user_id:uid,import_batch_id:batch.id,import_file_id:file?.id||null,original_description:row.original,normalized_description:row.normalized,merchant_name:row.merchant,transaction_date:row.date||null,amount:Number(row.amount)||0,type:row.type==='Crédito'?'credit':row.type==='Estorno'?'refund':row.type==='Juros'?'interest':row.type==='Tarifa'?'fee':'expense',installment_number:row.installmentNumber?Number(row.installmentNumber):null,installment_total:row.installmentTotal?Number(row.installmentTotal):null,confidence:row.confidence||'unclassified',review_status:draft.status||'pending',note:row.note,raw_data:{filename,category:row.category,subcategory:row.subcategory,page:row.page}}]);}}notify('Revisão salva no Supabase como rascunho.');};
  const loadRemote=async()=>{try{const uid=userId();if(!uid)return notify('Entre novamente para carregar a revisão.',true);const batches=await window.clarezaDb.select('import_batches',`?user_id=eq.${uid}&status=eq.review&order=created_at.desc&limit=1`);if(!batches.length)return notify('Nenhuma revisão remota encontrada.',true);const rows=await window.clarezaDb.select('import_rows',`?user_id=eq.${uid}&import_batch_id=eq.${batches[0].id}`);const drafts=read();rows.forEach(item=>{const filename=item.raw_data?.filename;if(!filename)return;drafts[filename]=drafts[filename]||{rows:[],status:'Em revisão'};drafts[filename].rows.push({id:item.id,date:item.transaction_date,original:item.original_description,normalized:item.normalized_description,merchant:item.merchant_name,amount:item.amount,type:item.type==='credit'?'Crédito':item.type==='refund'?'Estorno':item.type==='interest'?'Juros':item.type==='fee'?'Tarifa':'Compra',category:item.raw_data?.category,subcategory:item.raw_data?.subcategory,page:item.raw_data?.page,note:item.note});});localStorage.setItem(draftKey,JSON.stringify(drafts));notify('Revisão remota carregada no rascunho local.');location.reload();}catch(error){notify(error.message,true);}};
  const observer=new MutationObserver(addButtons);observer.observe(document.body,{childList:true,subtree:true});addButtons();
})();
